//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Admin
    {
        [Key]
        public string id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }

        [EmailAddress]
        [Required(ErrorMessage ="Lutfen mail adresini giriniz")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Lutfen sifre giriniz")]
        [DataType(DataType.Password)]
        [Display(Name ="Sifre")]
        public string Password { get; set; }
    }
}
