//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int id { get; set; }
        public int SenderId { get; set; }
        public string konu { get; set; }
        public string problem { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public System.DateTime tarih { get; set; }
        public short okundu { get; set; }
    }
}
